name = "tenbou-backend"
main = "src/index.ts"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "tenbou"
database_id = "67fd62eb-7f04-4310-96a3-3e31bf748c9b"

